[package]
name = "egglog-experimental"
version = "3.0.0"
edition = "2024"
description = "Experimental extensions to the egglog language."
repository = "https://github.com/egraphs-good/egglog-experimental"
keywords = ["e-graphs", "egglog", "datalog", "compiler", "equality"]
license = "MIT"
readme = "README.md"

[[test]]
harness = false
name = "files"

[features]
default = ["bin"]
bin = ["egglog/bin"]

[dependencies]
egglog = { version = "3.0.0", git = "https://github.com/egraphs-good/egglog", rev = "a07403c05fd5727d55ebf254013b3dd361bd67f6", default-features = false }
egglog-ast = { version = "3.0.0", git = "https://github.com/egraphs-good/egglog", rev = "a07403c05fd5727d55ebf254013b3dd361bd67f6", default-features = false }
egglog-reports = { version = "3.0.0", git = "https://github.com/egraphs-good/egglog", rev = "a07403c05fd5727d55ebf254013b3dd361bd67f6", default-features = false }

num = "0.4.3"
lazy_static = "1.4"
log = "0.4"

[dev-dependencies]
glob = "0.3.1"
libtest-mimic = "0.8.1"
